### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by acoulton** [smirik/php-datetime-ago#8]
This looks like a useful package, thank you for sharing it! Just wondering, the last release is a couple of years old and seems to be quite a few commits behind (including some bugfixes etc). Could you release a 1.1 / 1.0.2?

**Comment by smirik** [comment]
Sure, let's release v1.1.0

**Comment by smirik** [comment]
Done.

**Comment by acoulton** [comment]
@smirik thanks for the quick response, and apologies for targeting #9 and #10 to the wrong branch.
